name: jung-test-az-func
on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  NODE_VERSION: "18.x"
  ENV_NAME: ${{ (github.ref == 'refs/heads/main' && 'production') || 'development' }}

jobs:
  build-and-deploy:
    name: Build and deploy to an Azure Function
    runs-on: ubuntu-20.04
    environment: ${{ (github.ref == 'refs/heads/main' && 'production') || 'development' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install
        run: |
          npm install
      - name: npm run build
        run: |
          npm run build
      - name: Deploy Azure Functions Action
        uses: Azure/functions-action@v1.3.1
        with:
          app-name: ${{ vars.APP_NAME }}
          package: "."
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
